import { Application } from 'express'
import { getTemplate } from '../modules/template'

const router = (app: Application) => {
  // HTML templates are generated by webpack.
  // You can get html string by accessing "global.templates[pageName]".

  // Index.
  app.get('/', (req, res, next) => {
    res.setHeader('Content-Type', 'text/html')
    res.send(getTemplate('index'))
  })

  // About.
  app.get('/about', (req, res, next) => {
    res.send(getTemplate('about'))
  })

  // 404.
  app.use((req, res) => {
    res.status(404).send('404 Not found')
  })

  // Other errors.
  app.use((req, res) => {
    res.status(500).send('500 Internal error')
  })
}

export {
  router
}
