export default function router (app) {
  // HTML templates are generated by webpack.
  // You can get html string by accessing "global.templates[pageName]".

  // Index.
  app.get('/', (req, res, next) => {
    res.setHeader('Content-Type', 'text/html')
    res.send(getTemplate('index'))
  })

  // About.
  app.get('/about', (req, res, next) => {
    res.send(getTemplate('about'))
  })

  // 404 Error.
  app.use((req, res, next) => {
    const error = new Error('Not Found')
    error['status'] = 404
    next(error)
  })

  // 500 Error.
  app.use((error, req, res, next) => {
    const status = error.status || 500
    res.status(status).send({
      status,
      msg: error.message
    })
  })
}

function getTemplate (pageName = 'index') {
  return global['templates'][pageName]
}